update maintain

diff --git a/maintain b/maintain
--- a/maintain
+++ b/maintain
@@ -35,5 +35,17 @@ sudo journalctl --vacuum-time=2weeks
 echo "=== Updating mirror list with reflector ==="
 sudo reflector --verbose --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
 
+echo "=== Updating native packages ==="
+
+while true; do
+    if ! yay --noconfirm; then
+        echo "ERROR: yay update failed"
+        echo "Retrying..."
+    else
+        echo "SUCCESS: yay update completed"
+        break
+    fi
+done
+
 echo "=== System maintenance complete! ==="
 
